### ISSUE TITLE
Question/notes about compiling TangoSourceDistribution

### ISSUE THREAD

**Issue by cmft** [tango-controls/TangoSourceDistribution#11]
I'm testing the master branch on Debian 9 and I found some troubles:

`ant clean` reports this problem:
```
cleanup-distribution:
     [exec] mv: cannot stat 'doc/src/ds_model/zmq_event.fig': No such file or directory
     [exec] /homelocal/cfalcon/tools/TangoSourceDistribution/cleanup_distrib: line 113: cd: doc/src: No such file or directory
     [exec] /homelocal/cfalcon/tools/TangoSourceDistribution/cleanup_distrib: line 114: ./add_lic: No such file or directory

build:
     [echo] Done!
```

`ant build package` seems to work, it creates a source dir and a tar file

```
...
package:
    [mkdir] Created dir: /homelocal/cfalcon/tools/TangoSourceDistribution/build/package/tango-9.3.2
  [copydir] DEPRECATED - The copydir task is deprecated.  Use copy instead.
  [copydir] Copying 711 files to /homelocal/cfalcon/tools/TangoSourceDistribution/build/package/tango-9.3.2
      [tar] Building tar: /homelocal/cfalcon/tools/TangoSourceDistribution/build/tango-dev.tar.gz
```

but if I try to compile the generated sources 
```
cd /homelocal/cfalcon/tools/TangoSourceDistribution/build/package/tango-9.3.2
./configure
bash: ./configure: Permission denied

Quickly comparing the previous tar source (9.2.5a) with the generated sources there are several files with different permissions 

```
If I manually fix the permission of configure file, after run it, I got this error.
```
./configure
...
config.status: creating tests/Makefile
config.status: error: cannot find input file: `doc/Makefile.in'
configure: error: ./configure failed for lib/cpp/log4tango
```

What i'm doing wrong?

**Comment by Ingvord** [comment]
@cmft, `ant clean` reports this problem:

```
cleanup-distribution:
     [exec] mv: cannot stat 'doc/src/ds_model/zmq_event.fig': No such file or directory
     [exec] /homelocal/cfalcon/tools/TangoSourceDistribution/cleanup_distrib: line 113: cd: doc/src: No such file or directory
     [exec] /homelocal/cfalcon/tools/TangoSourceDistribution/cleanup_distrib: line 114: ./add_lic: No such file or directory
```

Should be fixed in 6b48cd6

**Comment by Ingvord** [comment]
@cmft , 

`bash: ./configure: Permission denied`

this is due to `ant copy` task used underlying: [link](https://stackoverflow.com/a/1517389/4232362)

Please, use `build/distr` for local testing.

**Comment by Ingvord** [comment]
@cmft ,

```
./configure
...
config.status: creating tests/Makefile
config.status: error: cannot find input file: `doc/Makefile.in'
configure: error: ./configure failed for lib/cpp/log4tango
```

Should be fixed in db73d5c

**Comment by Ingvord** [comment]
@cmft ,

After #12 resulting tar must have valid permissions for *configure* and others. *package* is an intermediate step so as before for local testing please use *build*/*distr* or unpack resulting tar.

Thanks for this notes and testing new TangoSourceDistribution build process!

Please feel free to re-open this issue if fixes above does not work for you.

**Comment by cmft** [comment]
Hi @Ingvord , 
All the reported issues have been fixed. I found another trouble with the log4tango doc generation using the tar file. The debian package uses this command and it fails. 

```
make -C lib/cpp/log4tango/doc
make: Entering directory '/homelocal/cfalcon/tools/TangoSourceDistribution/build/tango-9.3.2/lib/cpp/log4tango/doc'
Makefile:716: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
make: Leaving directory '/homelocal/cfalcon/tools/TangoSourceDistribution/build/tango-9.3.2/lib/cpp/log4tango/doc'
```

**Comment by Ingvord** [comment]
@cmft , should be fixed in 2a11920

**Comment by cmft** [comment]
Many thanks @Ingvord ,
All the reported bug have been fixed and i could go beyond but I found more troubles.

-  log4tango/doc makefile fails:
```
make -C lib/cpp/log4tango/doc
make: Entering directory '/homelocal/cfalcon/tools/TangoSourceDistribution/build/tango-9.3.2/lib/cpp/log4tango/doc'
Makefile:716: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
make: Leaving directory '/homelocal/cfalcon/tools/TangoSourceDistribution/build/tango-9.3.2/lib/cpp/log4tango/doc'
```
- DataBaseds is missing

**Comment by Ingvord** [comment]
@cmft 

> log4tango/doc makefile fails:

Isn't it the same that should be fixed in 2a11920 ? Have you updated your git repo?

> DataBaseds is missing

What do you mean? It should be missing because log4tango is not built. Or it is something different?

**Comment by cmft** [comment]
Sorry for repeated bug report (i did twice by mistake). I thought I did not report it. 

I'm building the debian package and it is looking for it.
You are right, I did manual compilation of the sources and both (9.2.5 and 9.3.2) look like equals. I have to figure out how is generating it in the debian package

**Comment by cmft** [comment]
From #13 I found what is missing in the Debian rules. It is not a trivial changed.
There is a way to not force `mariadb` ?

```
DB_INC := $(shell mysql_config --variable=pkgincludedir)
DB_LIB := $(shell mysql_config --variable=pkglibdir)

CONFIGURE_OPTS := --with-omni=/usr --disable-static --disable-dbcreate --disable-java --with-doxygen --disable-jpegmmx --enable-mariadb --with-mysql-admin=root --with-mariadbclient-include=$(DB_INC) --with-mariadbclient-lib=$(DB_LIB) --enable-dbcreate --enable-dbserver=yes
```
