### ISSUE TITLE
TangoRestServer status is not updated in astor

### ISSUE THREAD

**Issue by mliszcz** [tango-controls/TangoSourceDistribution#24]
I have configured TangoRestServer to be controlled by Astor. The process is started correctly, nothing suspicious in Starter's or server's logs. Still there's a red dot in Astor:
![obraz](https://user-images.githubusercontent.com/6927259/56197347-efda3180-6038-11e9-8c41-b92dfe597232.png)

Seems that the issue is due to a repeated instance name (`$* $@`):
https://github.com/tango-controls/TangoSourceDistribution/blob/8a438ac4d69cb70f9f4a15670de76c71fa2794eb/assets/lib/java/TangoRestServer.in#L13

I do not know what arguments TangoRestServer expects, but per wiki docs it shall be:
```
$INSTANCE_NAME org.tango.TangoRestServer $INSTANCE_NAME
```

So I propose to use a more robust approach (guarantee that there is a single instance argument, quote strings and pass remaining arguments , if any):
```bash
[[ $# -le 1 ]] && exit 1
INSTANCE ="$1"
shift
... -jar $TANGO_REST_SERVER_JAR "$INSTANCE" org.tango.TangoRestServer "$INSTANCE" "$@"
```

Edit: also quote $INSTANCE

**Comment by Ingvord** [comment]
Fine with me
