### ISSUE TITLE
cmake opt files missing

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/TangoSourceDistribution#34]
The following files are missing to enable the possibility to generate CMakeLists.txt files from Pogo when generating code for a C++ device server:
- cmake_common_target.opt.in
- cmake_tango.opt.in

These files should be under assets/pogo/preferences

**Comment by mliszcz** [comment]
@bourtemb, do you know where those files are stored? I was unable to find them in pogo source tree. Do we need to write them from a scratch?

**Comment by bourtemb** [comment]
Yes, we need to write them from scratch. There is no example provided by the POGO repo.
We have an example in use here at the ESRF but we will need to tailor it to fit the needs of the TangoDistribution.
I will propose a PR this week with a first version so we could discuss and get a version to include in the TangoSourceDistribution.

**Comment by bourtemb** [comment]
Fixed by #36
