### ISSUE TITLE
Failed to get the inputStream for file resource: pom.properties

### ISSUE THREAD

**Issue by aureocarneiro** [tango-controls/TangoSourceDistribution#38]
Hey in this latest version, 9.3.3, when I open Astor I receive these logs:

```
Display is localhost:10.0
Failed to get the inputStream for file resource :	  pom.properties
Failed to get the inputStream for file resource :	  pom.properties
Failed to get the inputStream for file resource :	  pom.properties
Version: 7.2.5
Build  GUI :3630 ms
========== ZMQ (3.22) event system is available ============
Total time to subscribe on 65 hosts : 6999 ms
Total time to start Astor 9287 ms
```

Is this "Failed to get the inputStream for file resource : pom.properties" normal or is it a bug in my build?

Thanks!

**Comment by bourtemb** [comment]
Hi @aureocarneiro ,

I can see the same messages as you when I use astor installed from 9.3.3 Tango source distribution on a VM.
@Pascal-Verdier , could you please tell us whether these errors are normal or the sign of something wrong with the source distribution? And could you please guide us on where to look to fix the issue.
When I start astor 7.2.5 from our ESRF installation, I don't see these messages.

**Comment by Pascal-Verdier** [comment]
This is just a warning trace.
It has been removed in Astor-7.2.6
