### ISSUE TITLE
CI builds are failng ('ant' is currently not installed)

### ISSUE THREAD

**Issue by mliszcz** [tango-controls/TangoSourceDistribution#44]
https://travis-ci.org/tango-controls/TangoSourceDistribution/builds/568237797?utm_source=github_status&utm_medium=notification

```
$ ant build package
The program 'ant' is currently not installed. To run 'ant' please ask your administrator to install the package 'ant'
The command "ant build package" exited with 127.
```

Probably ant was removed from travis java environment and shall be installed manually.

**Comment by bourtemb** [comment]
Fixed in #45
