### ISSUE TITLE
Remove the default Java logback file?

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/TangoSourceDistribution#46]
Latest JTango release (9.5.15) provides a reasonable default logback configuration which logs to the console with reasonable levels for Tango and JacORB logging, when no logback file is provided.
Shall we revert what was done in commit https://github.com/tango-controls/TangoSourceDistribution/pull/18/commits/834c5b64e6184ea3b0cd0fd6e380661175b82f28 from #18 and remove the default logback file?

**Comment by Ingvord** [comment]
I would leave it. If someone will use this distribution to develop Tango Java apps it would be more convenient to use explicit file to configure logs

**Comment by bourtemb** [comment]
OK, let's leave it like that and close this issue.
