### ISSUE TITLE
Prepare 9.3.4-rc2

### ISSUE THREAD

**Issue by t-b** [tango-controls/TangoSourceDistribution#56]
- [x] https://github.com/tango-controls/cppTango/pull/621
- [x] https://github.com/tango-controls/starter/pull/7
- [x] https://github.com/tango-controls/TangoDatabase/pull/20
- [x] https://github.com/tango-controls/TangoSourceDistribution/pull/55
- [x] Create new releases for TangoDatabase/cppTango
- [x] Create new release for starter (needs mighty user)
- [x] Update distribution.properties
- [x] Tag repo
- [x] Ping picca

**Comment by picca** [comment]
Hello, I am still preparing the Debian package :)

I have these errors  via lintian

E: tango source: source-is-missing doc/html/_static/astor_new_server_wizard.swf

do you have the source of this swf file ?

E: tango source: source-is-missing doc/html/_static/jquery.js line length is 32033 characters (>512)
E: tango source: source-is-missing doc/html/_static/underscore.js line length is 519 characters (>512)
E: tango source: source-is-missing doc/html/_static/js/modernizr.min.js
E: tango source: source-is-missing doc/html/_static/js/theme.js line length is 505 characters (>256)

I can deal with this by removing the pre-build documentation, like I do with the .jar files.
Nevertheless, it would be nice to avoid pre-buildding documentation.

E: tango source: source-is-missing doc/src/source/_static/astor_new_server_wizard.swf

idem sources ?

E: tango source: source-is-missing doc/src/source/_theme/sphinx_rtd_theme/static/js/modernizr.min.js
E: tango source: source-is-missing doc/src/source/_theme/sphinx_rtd_theme/static/js/theme.js line length is 505 characters (>256)

What is the purpose of these two files ?

On Debian we already have rtd packages
python3-sphinx-rtd-theme/stable 0.4.3+dfsg-1 all
  sphinx theme from readthedocs.org (Python 3)

sphinx-rtd-theme-common/stable,now 0.4.3+dfsg-1 all
  sphinx theme from readthedocs.org (common files)

Cheers

**Comment by bourtemb** [comment]
> Hello, I am still preparing the Debian package :)

Thanks!

> I have these errors via lintian
> 
> E: tango source: source-is-missing doc/html/_static/astor_new_server_wizard.swf
> 
> do you have the source of this swf file ?

This is a very old file. It seems it was some kind of video showing the wizard in action. 
We don't have the sources and it even doesn't seem to work anymore:
https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/built-in/astor/new_server_wizard.html

This should be removed, or better, replaced with something else (series of pictures? Animated image?)...
@piogor, could you please take care of that?

> E: tango source: source-is-missing doc/html/_static/jquery.js line length is 32033 characters (>512)
> E: tango source: source-is-missing doc/html/_static/underscore.js line length is 519 characters (>512)

I don't see these crazy lines in these files...? 

> E: tango source: source-is-missing doc/html/_static/js/modernizr.min.js
> E: tango source: source-is-missing doc/html/_static/js/theme.js line length is 505 characters (>256)

These 2 files have indeed some very long lines.... @piogor, can we do something about it?

> 
> I can deal with this by removing the pre-build documentation, like I do with the .jar files.
> Nevertheless, it would be nice to avoid pre-buildding documentation.

Maybe we don't need it indeed.
If our users want to have a look at the documentation, they will usually go to https://tango-controls.readthedocs.io directly.
And if they need offline doc, then, they can probably build it themselves?
> 
> E: tango source: source-is-missing doc/src/source/_static/astor_new_server_wizard.swf
> 
> idem sources ?

idem. We don't have them.

> E: tango source: source-is-missing doc/src/source/_theme/sphinx_rtd_theme/static/js/modernizr.min.js
> E: tango source: source-is-missing doc/src/source/_theme/sphinx_rtd_theme/static/js/theme.js line length is 505 characters (>256)
> 
> What is the purpose of these two files ?

@piogor, do you know? I think we have a customized rtd theme for Tango, haven't we?

> 
> On Debian we already have rtd packages
> python3-sphinx-rtd-theme/stable 0.4.3+dfsg-1 all
> sphinx theme from readthedocs.org (Python 3)
> 
> sphinx-rtd-theme-common/stable,now 0.4.3+dfsg-1 all
> sphinx theme from readthedocs.org (common files)
> 
> Cheers

**Comment by picca** [comment]
> E: tango source: source-is-missing doc/html/_static/jquery.js line length is 32033 characters (>512)
> E: tango source: source-is-missing doc/html/_static/underscore.js line length is 519 characters (>512)

> I don't see these crazy lines in these files...?

> E: tango source: source-is-missing doc/html/_static/js/modernizr.min.js
> E: tango source: source-is-missing doc/html/_static/js/theme.js line length is 505 characters (>256)

> hese 2 files have indeed some very long lines.... @piogor<https://github.com/piogor>, can we do something about it?

> I can deal with this by removing the pre-build documentation, like I do with the .jar files.
> Nevertheless, it would be nice to avoid pre-buildding documentation.

> Maybe we don't need it indeed.
> If our users want to have a look at the documentation, they will usually go to https://tango-controls.readthedocs.io directly.
> And if they need offline doc, then, they can probably build it themselves?

so maybe avoid building the documentation would be simpler.
I had to patch the build system in order to avoid installation of the docuymentation via
make install

On Debian we have profile for building (it simplify bootstrapping of new architectures).
https://wiki.debian.org/BuildProfileSpec

So I use the <!nodoc> in order to tag the Build Dependency.

there is two kind of binary package.

architecture dependant package (any, amd64, i686, ...) (build on all architectures)
non-architecture dependant packages (all) (build only one for all architecture)

Usualy the documentation is arch all.

so the build system MUST allow to build both part of a package independently, this is why  building and ionstalling the documentation is better, if there is dedicated
targets.


Cheers

**Comment by t-b** [comment]
@picca @bourtemb How about we do fix theses after the merging #55 and releasing rc2?

**Comment by picca** [comment]
> @picca<https://github.com/picca> @bourtemb<https://github.com/bourtemb> How about we do fix theses after the merging #55<https://github.com/tango-controls/TangoSourceDistribution/pull/55> and releasing rc2?

no problem for me, less issues, is always better :))

**Comment by t-b** [comment]
@picca Next rc is out.

**Comment by t-b** [comment]
@picca @bourtemb If possible I would favour having separate issues for tackling debian packaging requirements. Comments in an issue are quickly lost.

Regrading the too long lines, minified javascript files have these very often.

I would be in favour of keeping the documentation in the source package here as it is convenient for users.
