### ISSUE TITLE
Release 9.3.4-rc5

### ISSUE THREAD

**Issue by t-b** [tango-controls/TangoSourceDistribution#77]
- [x] Raise version JTango, see https://github.com/tango-controls/JTango/issues/101
- [x] cppTango 9.3.4-rc5
- [x] https://github.com/tango-controls/TangoSourceDistribution/issues/73
- [x] https://github.com/tango-controls/TangoDatabase/issues/21
- [x] Tag new TangoDatabase and include

**Comment by cpascual** [comment]
Hi, any ETA on this? 
We would love to be able to build a package and docker images based on this to check if it fixes [our issues in CI](https://github.com/taurus-org/taurus/issues/1042) that we suspect are caused by tango-controls/cppTango#699

**Comment by t-b** [comment]
@cpascual We don't have an ETA yet. But I created a PR with the current state. You can use that to build a tango source distribution locally. Does that help?

**Comment by cpascual** [comment]
Yes, I will try using #79 to build locally. Thanks for the suggestion!

note: maybe it would be helpful if travis would be configured to keep artifacts for PRs such as this one (not deploying to release, but just keep the built tar.gz as an artifact in the build)

**Comment by t-b** [comment]
travis has no support for storing the artifacts itself.

**Comment by cpascual** [comment]
Oh, I see... of course you are right! (I've been working with gitlab-ci lately and I got confused! )  ;-)
