### ISSUE TITLE
Final release 9.3.4

### ISSUE THREAD

**Issue by t-b** [tango-controls/TangoSourceDistribution#87]
- [x] New TangoAccessControl, tag it before
- [ ] Check if cppTango 9.3-backports branch got changes
- [x] TangoTest new release, https://github.com/tango-controls/TangoTest/releases/tag/3.0
- [x] New JTango (9.6.7) solving tango-controls/JTango#90 
- [x] Update jive to 7.25

**Comment by bourtemb** [comment]
The following software parts got new releases recently:
- jtango: 9.6.1 -> 9.6.6
- jive: 7.23 -> 7.25
- atk: 9.3.14 -> 9.3.19
- atk-panel: 5.8 -> 5.9
- astor: 7.2.10 -> 7.3.5  (@Pascal-Verdier , can we upgrade the version provided with the Tango Source Distribution to 7.3.5 ? (java 8 support mandatory))
- log-viewer: 2.05 -> 2.10
- rest-server: 1.22 -> 2.1  (**!!Old API no longer supported in this version!!**)
- TangoTest: 2.1 -> 3.0

Pogo got new releases too but no new release after 9.6.31 which would be java-8 friendly I believe.

@ingvord, we've seen there were new releases of the rest-server but it seems support for the old Rest API versions have been dropped in the latest releases.
Which version should we provide with the coming Tango Source Distribution release (9.3.4)?
Should we wait for Tango Source Distribution 9.4 to provide a rest-server 2x version?

**Comment by Ingvord** [comment]
@bourtemb, 

I would leave the old version for now. Thanks!

**Comment by t-b** [comment]
@bourtemb rc7 or the final release?

**Comment by bourtemb** [comment]
> @bourtemb rc7 or the final release?

@t-b, do you mean rc8?
Let's discuss that during the Kernel Meeting.
If there is no big issue identified, I would go for the final release.

>     * astor: 7.2.10 -> 7.3.5  (@Pascal-Verdier , can we upgrade the version provided with the Tango Source Distribution to 7.3.5 ? (java 8 support mandatory))

@Pascal-Verdier confirmed to me that we can provide the latest astor release, which is still java 8 friendly.

**Comment by t-b** [comment]
Yes I meant rc8.
