### ISSUE TITLE
zlib >= 1 

### ISSUE THREAD

**Issue by lorenzopivetta** [tango-controls/TangoSourceDistribution#88]
configure requires zlib >= 1. Not sure when this has been introduced, but prevents to build on PPC legacy platforms (zlib 0.9)

**Comment by t-b** [comment]
Can you post the configure log file?
Can you not update zlib? According to https://www.zlib.net/ChangeLog.txt 1.0.1 came out in May 1996.

@bourtemb The only thing which needs zlib in cppTango is the server-side jpeg support. Maybe we can allow to not build that?

**Comment by t-b** [comment]
@lorenzopivetta IIRC you are running debian on that? Which version?

**Comment by lorenzopivetta** [comment]
Running Ubuntu 7.10 on PPC. Passing --disable-jpegmmx to configure does not make it work, see the last output line form:

../configure --prefix=/usr/local/tango-9.3.4-rc7 -with-omni=/usr/local/omniorb-4.2.3 --with-zmq=/usr/local/zeromq-4.0.8 --disable-static --disable-dbcreate --disable-dbserver --disable-jpegmmx

...
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZLIB... no
configure: error: Package requirements (zlib >= 1) were not met:

No package 'zlib' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ZLIB_CFLAGS
and ZLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by t-b** [comment]
Thx. So the bug is actually that we still look for zlib even when the jpeg support is disabled.

**Comment by lorenzopivetta** [comment]
Mmmhhh, not sure, I think the option disables mmx support for jpeg, not jpeg support itself

**Comment by t-b** [comment]
> Mmmhhh, not sure, I think the option disables mmx support for jpeg, not jpeg support itself

Yes, you are right. Would allowing to disable jpeg support work for you?

**Comment by t-b** [comment]
@lorenzopivetta Have you tried setting `ZLIB_CFLAGS` and `ZLIB_LIBS` as indicated in the error message?

**Comment by lorenzopivetta** [comment]
No, should not be required... since the package is installed. The problem is it's release 0.9

**Comment by bourtemb** [comment]
@lorenzopivetta , did you try to run configure with `--without-zlib` option as suggested by the README?

https://github.com/tango-controls/TangoSourceDistribution/blob/ff33b5af6ac69bc5c68f7c4817845535be52d270/assets/README#L300-L301

**Comment by bourtemb** [comment]
It looks like zlib might be needed to compile the database server.
I guess you don't need to compile the Database Server in your case?
So you could also try to run configure with  `--disable-dbserver` option too? Maybe this is also removing the dependency to zlib?

**Comment by lorenzopivetta** [comment]
Just tried with --without-zlib, with no luck. Still looking for it. Moreover I'm already disabling lots of builds:

../configure --prefix=/usr/local/tango-9.3.4-rc7 -with-omni=/usr/local/omniorb-4.2.3 --with-zmq=/usr/local/zeromq-4.0.8 --disablestatic --disable-dbcreate --disable-dbserver --disable-jpegmmx --without-zlib

**Comment by bourtemb** [comment]
Did you do that from a clean build directory?
I don't know how the autotools are working but maybe there is some cache involved?

**Comment by lorenzopivetta** [comment]
Yes, freshly made "build" dir

**Comment by t-b** [comment]
My patch in https://github.com/tango-controls/TangoSourceDistribution/commit/ba2e581a35213f48162a488b24094b360b09916c lost the --without-zlib option. I'll prepare a patch. 

@lorenzopivetta Can you remove the line `PKG_CHECK_MODULES([ZLIB], [zlib >= 1])`, execute `./bootstrap` and try again?

**Comment by lorenzopivetta** [comment]
Hi @t-b unfortunately there's no bootstrap in the main folder in the tarball, I'm picking the one in TangoSourceDistribution repository. On the target it fails at the first aclocal command, I think the system is too old. Made the bootstrap steps on a different host, and now the configure command succeeds on PPC.
Building the tango lib now, it will take some time.

**Comment by lorenzopivetta** [comment]
At a very preliminary test 9.3.4-rc7 is working on PPC, Ubuntu 7.10, kernel 2.6.25
