### ISSUE TITLE
Ubuntu 18.04.5 LTS i686 build

### ISSUE THREAD

**Issue by lorenzopivetta** [tango-controls/TangoSourceDistribution#91]
Hi,
just trying to build tango-9.3.4-rc7 on an Ubuntu 18.04.5 i686 (yes, that's a 32 bit system...). The library builds, but then the build fails when building utils (e.g. cannot compile an executable using libtango):

...
Making all in utils
make[2]: Entering directory '/usr/local/src-compiled/packages/tango-9.3.4-rc7/build/utils'
Making all in tango_admin
make[3]: Entering directory '/usr/local/src-compiled/packages/tango-9.3.4-rc7/build/utils/tango_admin'
  CXXLD    tango_admin
/usr/local/src-compiled/packages/tango-9.3.4-rc7/build/lib/cpp/client/.libs/libtango.so: undefined reference to `__i686.get_pc_thunk.bx'
collect2: error: ld returned 1 exit status
Makefile:500: recipe for target 'tango_admin' failed
make[3]: *** [tango_admin] Error 1
make[3]: Leaving directory '/usr/local/src-compiled/packages/tango-9.3.4-rc7/build/utils/tango_admin'
Makefile:439: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/src-compiled/packages/tango-9.3.4-rc7/build/utils'
Makefile:528: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src-compiled/packages/tango-9.3.4-rc7/build'
Makefile:460: recipe for target 'all' failed
make: *** [all] Error 2

as it is not resolving __i686.get_pc_thunk.bx. At a quick look seems that's a PIC loader... suspect this may be related to the g++ version, that's 7.5.0
`$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/7/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=i686-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)`

Any feedback?
Thanks,
Lorenzo

**Comment by t-b** [comment]
No immediate ideas, I'll try to reproduce.

**Comment by t-b** [comment]
I can replicate that with debian 8  jessie 32bit.

**Comment by t-b** [comment]
@lorenzopivetta A fix is available in https://github.com/tango-controls/cppTango/pull/783.

You can grab that fix also locally via

```
cd $tango-source-build-package
cd lib/cpp
wget -L https://github.com/tango-controls/cppTango/commit/8d0bd12e18aa7ea5dad4642790e68499705623b7.patch
patch -p2 < 8d0bd12e18aa7ea5dad4642790e68499705623b7.patch
```

Another fix is to disable jpeg mmx.

**Comment by lorenzopivetta** [comment]
Thanks @t-b , just built 9.3.4 and a tango device for test.

**Comment by t-b** [comment]
Fix is merged in cppTango.
