### ISSUE TITLE
Gitlab Migration: Please log into GL with your GH account ASAP

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/TangoSourceDistribution#97]
Dear TangoSourceDistribution participant (via commits, comments on issue or pull requests, issue creator),

If you have contributed in any way (commit, issue or Pull Request creation or comment) to TangoSourceDistribution , please log into Gitlab.com using your Github account **ASAP**.
See https://github.com/tango-controls/TangoTickets/issues/47 for details.

For convenience, here is the list of contributors we could already find (and who did not signal they had done it yet for another repo):
- [ ] @Diego91RA, 
- [ ] @Pascal-Verdier, 
- [ ] @aureocarneiro, 
- [ ] @gwen-soleil, 
- [ ] @lorenzopivetta, 
- [ ] @sergirubio, 
- [ ] @tanj, 
- [ ] @taurel

Please click on the following link and add your github account name to this [framapad](https://mensuel.framapad.org/p/migration_ready_2548763689) when you've already done the login to Gitlab.com using your Github account:
https://mensuel.framapad.org/p/migration_ready_2548763689

Please note that login on gitlab.com using your Github account is safe and doesn't give your Github password to Gitlab.

Thanks for your cooperation.

**Comment by t-b** [comment]
The TangoSourceDistribution gitlab migration is foreseen on Thursday 21st January 2021.
So if you're mentioned above, please associate your Gitlab account to your GitHub account before that date or connect on Gitlab.com using the GitHub sign in button before that date.
Thanks in advance.

@bourtemb I stole your text.
